app:
  name : "Shop"
  mode : "Dev"
  port : 8080

log:
  level : "debug"
  filename : "WebApp.log"
  max_size : 500
  max_backups : 5
  max_age : 30

mysql:
  host: "192.168.56.1"
  port: 3306
  user: "root"
  password: "zheshimima"
  dbname: "webapp"

redis:
  host: "172.18.217.232"
  port: 6379
  db : 0
  password : "zheshimima"
  pool_size : 100

rabbitmq:
  host: "172.18.217.232"
  port: 5672
  user: "frotten"
  password: "frotten"