app:
  name : "Shop"
  mode : "Dev"
  port : 9090
  start_time: "2026-03-01"
  machine_id: 1

log:
  level : "debug"
  filename : "Shop1.log"
  max_size : 500
  max_backups : 5
  max_age : 30

mysql:
  host: "192.168.56.101"
  port: 3306
  user: "bookuser"
  password: "zheshimima"
  dbname: "bookstore"

redis:
  host: "192.168.56.101"
  port: 6379
  db : 0
  password : "zheshimima"
  pool_size : 200

rabbitmq:
  host: "192.168.56.101"
  port: 5672
  user: "guest"
  password: "guest"