// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Me",
            "email": "frottenice@outlook.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/book/add": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员添加新书籍（需要管理员权限）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍管理（管理员）"
                ],
                "summary": "添加书籍（管理员）",
                "parameters": [
                    {
                        "description": "书籍信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddBookParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/book/delete/{book_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员根据书籍 ID 删除书籍（需要管理员权限）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍管理（管理员）"
                ],
                "summary": "删除书籍（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍 ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 书籍不存在 / 无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/book/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新书籍信息，book_id 为必填（需要管理员权限）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍管理（管理员）"
                ],
                "summary": "更新书籍信息（管理员）",
                "parameters": [
                    {
                        "description": "更新书籍参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateBookParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 书籍不存在 / 无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/order/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员获取所有待发货订单列表（需要管理员权限）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单管理（管理员）"
                ],
                "summary": "获取待发货订单列表（管理员）",
                "responses": {
                    "200": {
                        "description": "无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/order/orderShip": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员对指定订单执行发货操作（需要管理员权限）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单管理（管理员）"
                ],
                "summary": "订单发货（管理员）",
                "parameters": [
                    {
                        "description": "订单 ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderConfirmParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 订单不存在 / 无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/seckill/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员为指定书籍创建秒杀活动，设置秒杀价格、库存和时间（需要管理员权限）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "秒杀管理（管理员）"
                ],
                "summary": "创建秒杀活动（管理员）",
                "parameters": [
                    {
                        "description": "秒杀活动参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SeckillParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/seckill/down/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员将指定秒杀活动下架（状态置为 0）（需要管理员权限）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "秒杀管理（管理员）"
                ],
                "summary": "下架秒杀活动（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "秒杀活动 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/admin/seckill/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员获取所有进行中的秒杀活动列表（需要管理员权限）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "秒杀管理（管理员）"
                ],
                "summary": "获取秒杀活动列表（管理员）",
                "responses": {
                    "200": {
                        "description": "无权限 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/AdminLogin": {
            "post": {
                "description": "管理员登录，成功后通过 Cookie 下发 access_token 和 refresh_token，同时在响应体中返回 access_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员认证"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "管理员登录参数（username、password）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Admin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 用户名或密码错误 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/AdminRegister": {
            "post": {
                "description": "注册新管理员账号，注册成功后自动跳转至管理员登录页面",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员认证"
                ],
                "summary": "管理员注册",
                "parameters": [
                    {
                        "description": "管理员注册参数（username、password）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Admin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 用户已存在 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/cart": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的购物车中所有商品（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "购物车"
                ],
                "summary": "获取购物车列表",
                "responses": {
                    "200": {
                        "description": "未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前登录用户购物车中指定书籍的数量（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "购物车"
                ],
                "summary": "更新购物车中书籍数量",
                "parameters": [
                    {
                        "description": "更新参数（book_id 和 quantity 必填）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CartParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录用户将书籍加入购物车，若未指定数量则默认为 1（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "购物车"
                ],
                "summary": "添加书籍到购物车",
                "parameters": [
                    {
                        "description": "购物车参数（book_id 必填，quantity 可选）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CartParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "清空当前登录用户购物车中的所有商品（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "购物车"
                ],
                "summary": "清空购物车",
                "responses": {
                    "200": {
                        "description": "未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/cart/{book_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从当前登录用户的购物车中移除指定书籍（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "购物车"
                ],
                "summary": "删除购物车中指定书籍",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "要删除的书籍 ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/comment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录用户对书籍发表评论，支持嵌套回复（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "发表书籍评论",
                "parameters": [
                    {
                        "description": "评论参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CommentParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/comment/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录用户对指定评论进行点赞（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "点赞评论",
                "parameters": [
                    {
                        "description": "评论点赞参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CommentLikeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/comments": {
            "get": {
                "description": "根据书籍 ID 获取该书籍的所有评论（树形结构）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "获取书籍评论列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍 ID",
                        "name": "book_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/getBookDetail/{book_id}": {
            "get": {
                "description": "通过书籍 ID 获取书籍详细信息（管理员和普通用户均可访问）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "根据书籍 ID 获取详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍 ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 书籍不存在 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/getBookTitle/{title}": {
            "get": {
                "description": "通过书名关键字模糊搜索书籍列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "根据书名搜索书籍",
                "parameters": [
                    {
                        "type": "string",
                        "description": "书名关键字",
                        "name": "title",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "书籍不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/getBooksBySaleJSON": {
            "get": {
                "description": "按书籍销量降序返回第 1 页书籍列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "获取书籍列表（第1页，按销量排序）",
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/getBooksBySaleJSON/{page}": {
            "get": {
                "description": "按书籍销量降序分页返回书籍列表，指定页码（每页 8 条）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "按销量分页获取书籍（指定页码）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（从 1 开始）",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/getBooksJSON": {
            "get": {
                "description": "按书籍评分降序返回第 1 页书籍列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "获取书籍列表（第1页，按评分排序）",
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/getBooksJSON/{page}": {
            "get": {
                "description": "按书籍评分降序分页返回书籍列表，指定页码（每页 8 条）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "按评分分页获取书籍（指定页码）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（从 1 开始）",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "用户登录，成功后通过 Cookie 下发 access_token 和 refresh_token，同时在响应体中返回 access_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ParamLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 用户名或密码错误 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/orderCancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户取消指定未支付订单（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "取消订单",
                "parameters": [
                    {
                        "description": "订单 ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderConfirmParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 订单不存在 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/orderConfirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户确认收货，订单状态变更为已完成（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "确认收货",
                "parameters": [
                    {
                        "description": "订单 ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderConfirmParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 订单不存在 / 重复操作 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/orderCreate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录用户根据购物车商品创建订单，成功后自动清空购物车（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "description": "订单创建参数（包含商品列表）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 库存不足 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/orderDetail/{order_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据订单 ID 获取订单详细信息（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "获取订单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单 ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 订单不存在 / 未登录",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/orderPay": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户支付指定订单（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "支付订单",
                "parameters": [
                    {
                        "description": "订单 ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderConfirmParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 订单不存在 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/rateBook": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录用户对书籍进行评分（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "对书籍评分",
                "parameters": [
                    {
                        "description": "评分参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRateBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "注册新用户，需要提供用户名、密码、确认密码、邮箱和性别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ParamSignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 用户已存在 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/seckill/do": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录用户参与指定秒杀活动抢购，成功后异步生成订单（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "秒杀"
                ],
                "summary": "参与秒杀",
                "parameters": [
                    {
                        "description": "秒杀参数（product_id 必填）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SeckillRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "未登录 / 参数错误 / 活动已结束 / 库存不足 / 重复参与",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/seckill/list": {
            "get": {
                "description": "获取当前所有进行中的秒杀活动（状态为上架）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "秒杀"
                ],
                "summary": "获取进行中的秒杀活动列表",
                "responses": {
                    "200": {
                        "description": "服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/seckill/{id}": {
            "get": {
                "description": "根据秒杀活动 ID 获取详细信息（包含书籍信息、价格、库存、时间等）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "秒杀"
                ],
                "summary": "获取秒杀活动详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "秒杀活动 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 活动不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/topSale": {
            "get": {
                "description": "获取销量最高的 Top 书籍列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "获取销量 Top 书籍",
                "responses": {
                    "200": {
                        "description": "服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/topScore": {
            "get": {
                "description": "获取综合评分最高的 Top 书籍列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "书籍"
                ],
                "summary": "获取评分 Top 书籍",
                "responses": {
                    "200": {
                        "description": "服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/userComments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户发表的所有评论（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户的评论列表",
                "responses": {
                    "200": {
                        "description": "未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/userInfo": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的基本信息（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/userOrders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的所有订单及订单详情（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "获取当前用户订单列表",
                "responses": {
                    "200": {
                        "description": "未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/userRatings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户对书籍的所有评分记录（需要登录）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户的评分记录",
                "responses": {
                    "200": {
                        "description": "未登录 / 服务器繁忙",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        },
        "/refreshtoken": {
            "post": {
                "description": "前端在 Access Token 过期时调用该接口，通过 Cookie 中的 refresh_token 换取新的 access_token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "刷新 Access Token",
                "responses": {
                    "200": {
                        "description": "无效的 Token",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddBookParam": {
            "type": "object",
            "required": [
                "author",
                "price",
                "publisher",
                "stock",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Admin": {
            "type": "object",
            "properties": {
                "admin_id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Book": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "book_id": {
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                },
                "price": {
                    "description": "Price和Score都用int64，前端显示时除以100,避免精度误差",
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "sales": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                },
                "tags": {
                    "description": "切片用法",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tag"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Cart": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "cart_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.CartParam": {
            "type": "object",
            "required": [
                "book_id"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.CommentBook": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "book_title": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "comment_id": {
                    "type": "integer"
                },
                "comment_time": {
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "parent_id": {
                    "description": "0表示一级评论",
                    "type": "integer"
                },
                "reply_count": {
                    "type": "integer"
                },
                "root_id": {
                    "description": "根评论ID（用于楼中楼）,一级评论的RootID为0，二级评论的RootID为一级评论的CommentID",
                    "type": "integer"
                },
                "status": {
                    "description": "1=正常 2=删除 3=审核中",
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "description": "仅用于返回给前端显示，不存储在数据库中",
                    "type": "string"
                }
            }
        },
        "models.CommentLikeParam": {
            "type": "object",
            "required": [
                "comment_id"
            ],
            "properties": {
                "comment_id": {
                    "type": "integer"
                }
            }
        },
        "models.CommentParam": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "comment": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "root_id": {
                    "type": "integer"
                }
            }
        },
        "models.OrderConfirmParam": {
            "type": "object",
            "required": [
                "order_id"
            ],
            "properties": {
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "models.OrderItem": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "price": {
                    "description": "下单时价格",
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.OrderParam": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.OrderRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/models.OrderParam"
                    }
                }
            }
        },
        "models.OrderView": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderItem"
                    }
                },
                "order_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "-1已删除 0未支付 1已支付待发货 2已发货待收货 3已收货",
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Page": {
            "type": "object",
            "properties": {
                "data": {},
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.ParamLogin": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ParamSignUp": {
            "type": "object",
            "required": [
                "email",
                "password",
                "re_Password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "email表示该字段必须是一个合法的邮箱格式",
                    "type": "string"
                },
                "gender": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "password": {
                    "description": "binding:\"required\"表示该字段为必填项",
                    "type": "string"
                },
                "re_Password": {
                    "description": "eqfield=Password表示该字段必须和Password字段相等",
                    "type": "string"
                },
                "username": {
                    "description": "json表示前端传过来的字段名，binding表示校验规则",
                    "type": "string"
                }
            }
        },
        "models.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {}
            }
        },
        "models.SeckillParam": {
            "type": "object",
            "required": [
                "book_id",
                "end_time",
                "seckill_price",
                "start_time",
                "stock"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "seckill_price": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "models.SeckillProductView": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "orig_price": {
                    "type": "integer"
                },
                "seckill_price": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.SeckillRequest": {
            "type": "object",
            "required": [
                "product_id"
            ],
            "properties": {
                "product_id": {
                    "type": "integer"
                }
            }
        },
        "models.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UpdateBookParam": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "book_id": {
                    "type": "integer"
                },
                "cover_image": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                },
                "price": {
                    "description": "Price和Score都用int64，前端显示时除以100,避免精度误差",
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "tags": {
                    "description": "切片用法",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.UserRateBook": {
            "type": "object",
            "properties": {
                "Op": {
                    "type": "integer"
                },
                "book_id": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.UserRating": {
            "type": "object",
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "book_title": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.UserView": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "格式：Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Project1_Shop API",
	Description:      "一个基于 Gin + GORM + Redis + RabbitMQ 的在线书店后端服务，提供用户认证、书籍管理、购物车、订单及秒杀等功能。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
